#!/bin/bash

# Script to checkout all the branches of the team
git checkout -b cine origin/cine
git checkout -b jaan origin/jaan
git checkout -b jobo origin/jobo
git checkout -b kewe origin/kewe
git checkout -b lyke origin/lyke
git checkout -b ribi origin/pbd
git checkout -b ribi origin/ribi
git checkout -b ribi origin/sado
