#!/bin/bash

cd ..

if [ ! -d BoostGraphTutorial ]; then
  git clone https://github.com/richelbilderbeek/BoostGraphTutorial
fi

cd BoostGraphTutorial
git pull
cd ..

if [ ! -d GSL ]; then
  git clone https://github.com/Microsoft/GSL
fi

cd GSL
git pull
cd ..

if [ ! -d gausser ]; then
  git clone https://github.com/richelbilderbeek/gausser
fi

cd gausser
git pull
cd ..

if [ ! -d Newick ]; then
  git clone https://github.com/richelbilderbeek/Newick
fi

cd Newick
git pull
cd ..

if [ ! -d SurfacePlotter ]; then
  git clone https://github.com/richelbilderbeek/SurfacePlotter
fi

cd SurfacePlotter
git pull
cd ..

if [ ! -d RibiClasses ]; then
  git clone https://github.com/richelbilderbeek/RibiClasses
fi

cd RibiClasses
git pull
cd ..

if [ ! -d RibiLibraries ]; then
  git clone https://github.com/richelbilderbeek/RibiLibraries
fi

cd RibiLibraries
git pull
cd ..

if [ ! -d RibiUnits ]; then
  git clone https://github.com/richelbilderbeek/RibiUnits
fi

cd RibiUnits
git pull
cd ..
