# Try to install from GitHub

# install.packages("ape", repos = "http://cran.uk.r-project.org")
# install.packages("adephylo", repos = "http://cran.uk.r-project.org")
# install.packages("BH", repos = "http://cran.uk.r-project.org")
# install.packages("clisymbols", repos = "http://cran.uk.r-project.org")
# install.packages("coda", repos = "http://cran.uk.r-project.org")
# install.packages("crayon", repos = "http://cran.uk.r-project.org")
# install.packages("cyclocomp", repos = "http://cran.uk.r-project.org")
# install.packages("data.table", repos = "http://cran.uk.r-project.org")
# install.packages("desc", repos = "http://cran.uk.r-project.org")
# install.packages("devtools", repos = "http://cran.uk.r-project.org")
# install.packages("ggplot2", repos = "http://cran.uk.r-project.org")
# install.packages("gridExtra", repos = "http://cran.uk.r-project.org")
# install.packages("httr", repos = "http://cran.uk.r-project.org")
# install.packages("Hmisc", repos = "http://cran.uk.r-project.org")
# install.packages("jsonlite", repos = "http://cran.uk.r-project.org")
# install.packages("knitr", repos = "http://cran.uk.r-project.org")
# install.packages("lubridate", repos = "http://cran.uk.r-project.org")
# install.packages("memoise", repos = "http://cran.uk.r-project.org")
# install.packages("phangorn", repos = "http://cran.uk.r-project.org")
# install.packages("PBD", repos = "http://cran.uk.r-project.org")
# install.packages("rcmdcheck", repos = "http://cran.uk.r-project.org")
# install.packages("rex", repos = "http://cran.uk.r-project.org")
# install.packages("roxygen2", repos = "http://cran.uk.r-project.org")
# install.packages("rmarkdown", repos = "http://cran.uk.r-project.org")
# install.packages("stringdist", repos = "http://cran.uk.r-project.org")
# install.packages("stringr", repos = "http://cran.uk.r-project.org")
# install.packages("testit", repos = "http://cran.uk.r-project.org")
# install.packages("testthat", repos = "http://cran.uk.r-project.org")
# install.packages("whoami", repos = "http://cran.uk.r-project.org")
# install.packages("withr", repos = "http://cran.uk.r-project.org")
# install.packages("XML", repos = "http://cran.uk.r-project.org")
# install.packages("xml2", repos = "http://cran.uk.r-project.org")

# devtools::install_github("ropensci/RNeXML")
# devtools::install_github("jimhester/covr")
# devtools::install_github("jimhester/lintr")
# devtools::install_github("richelbilderbeek/beastscriptr")
# devtools::install_github("olli0601/rBEAST")
devtools::install_github("richelbilderbeek/nLTT")
devtools::install_github("rsetienne/PBD", subdir = "PBD")
# devtools::install_github("MangoTheCat/goodpractice")
# devtools::install_github("beast-dev/RBeast")

warnings()
