#!/bin/bash

#SBATCH --time=12:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --ntasks=1
#SBATCH --mem=1G
#SBATCH --job-name=jobo_build
#SBATCH --output=jobo_build.log
module load Qt
module load GCC/5.1.0
module load Boost
module load Graphviz
qmake jobo_peregrine.pro
make release
./jobo_peregrine --create
