#!/bin/bash
#SBATCH --time=12:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --ntasks=1
#SBATCH --mem=1G
#SBATCH --job-name=Lykes_simulation2_run
#SBATCH --mail-type=BEGIN,END
#SBATCH --mail-user=l.e.stuurman@student.rug.nl
#SBATCH --output=lyke_simulation2_run.log
module load Qt
module load GCC/5.1.0
./lyke_peregrine