#!/bin/bash
git pull
git checkout master
git pull
git merge cine
git merge daic
git merge jaan
git merge jobo
git merge kewe
git merge pbd
git merge ribi
git merge sado
git push

git checkout cine; git merge master; git push
git checkout daic; git merge master; git push
git checkout jaan; git merge master; git push
git checkout jobo; git merge master; git push
git checkout kewe; git merge master; git push
git checkout pbd; git merge master; git push
git checkout ribi; git merge master; git push
git checkout sado; git merge master; git push



