#!/bin/bash

#SBATCH --time=12:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --ntasks=1
#SBATCH --mem=1G
#SBATCH --job-name=sado_build
#SBATCH --output=sado_build.log
module load git
module load Qt
module load GCC/5.1.0
module load Boost
module load Graphviz
./download_other_githubs
qmake sado_peregrine3.pro
make
./sado_peregrine3 --create
