#!/bin/bash
# Runs a PBD simulation from arguments, for example:
#   sbatch pbd_run 0.5 0.4 0.3 0.2 0.1 15.0 42 results.csv

#SBATCH --time=1:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --ntasks=1
#SBATCH --mem=100G
#SBATCH --job-name=pbd_run_from_args
#SBATCH --output=pbd_run_from_args-%j.log
module load Qt
module load GCC/5.1.0
module load R/3.3.1-foss-2016a
../pbd_peregrine $1 $2 $3 $4 $5 $6 $7 $8
