#!/bin/bash
# Runs a parameter file, for example:
#   sbatch pbd_run pbd.txt

#SBATCH --time=1:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --ntasks=1
#SBATCH --mem=100G
#SBATCH --job-name=pbd_run
#SBATCH --output=pbd_run-%j.log
module load Qt
module load GCC/5.1.0
module load R/3.3.1-foss-2016a
../pbd_peregrine $1
