#!/bin/bash
# Submit all jobs to redo the PBD article

#SBATCH --time=1:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --ntasks=1
#SBATCH --mem=100G
#SBATCH --job-name=pbd_jobscript
#SBATCH --output=pbd_jobscript.log
module load Qt
module load GCC/5.1.0
module load R/3.3.1-foss-2016a
../pbd_peregrine --version

for i in {1..10}
do
  # Submit the jobs
  #                        bg  bi  scr eg  ei  t  seed
  sbatch pbd_run_from_args 0.3 0.3 0.1 0.0 0.0 15 $i
  sbatch pbd_run_from_args 0.3 0.3 0.1 0.1 0.1 15 $i
  sbatch pbd_run_from_args 0.3 0.3 0.1 0.2 0.2 15 $i

  sbatch pbd_run_from_args 0.3 0.3 0.3 0.0 0.0 15 $i
  sbatch pbd_run_from_args 0.3 0.3 0.3 0.1 0.1 15 $i
  sbatch pbd_run_from_args 0.3 0.3 0.3 0.2 0.2 15 $i

  sbatch pbd_run_from_args 0.3 0.3 1.0 0.0 0.0 15 $i
  sbatch pbd_run_from_args 0.3 0.3 1.0 0.1 0.1 15 $i
  sbatch pbd_run_from_args 0.3 0.3 1.0 0.2 0.2 15 $i

  sbatch pbd_run_from_args 0.3 0.3 1000000 0.0 0.0 15 $i
  sbatch pbd_run_from_args 0.3 0.3 1000000 0.1 0.1 15 $i
  sbatch pbd_run_from_args 0.3 0.3 1000000 0.2 0.2 15 $i

  sbatch pbd_run_from_args 0.5 0.3 0.1 0.0 0.0 15 $i
  sbatch pbd_run_from_args 0.5 0.3 0.1 0.1 0.1 15 $i
  sbatch pbd_run_from_args 0.5 0.3 0.1 0.2 0.2 15 $i

  sbatch pbd_run_from_args 0.5 0.3 0.3 0.0 0.0 15 $i
  sbatch pbd_run_from_args 0.5 0.3 0.3 0.1 0.1 15 $i
  sbatch pbd_run_from_args 0.5 0.3 0.3 0.2 0.2 15 $i

  sbatch pbd_run_from_args 0.5 0.3 1.0 0.0 0.0 15 $i
  sbatch pbd_run_from_args 0.5 0.3 1.0 0.1 0.1 15 $i
  sbatch pbd_run_from_args 0.5 0.3 1.0 0.2 0.2 15 $i

  sbatch pbd_run_from_args 0.5 0.3 1000000 0.0 0.0 15 $i
  sbatch pbd_run_from_args 0.5 0.3 1000000 0.1 0.1 15 $i
  sbatch pbd_run_from_args 0.5 0.3 1000000 0.2 0.2 15 $i
  
done


