#!/bin/bash
#SBATCH --time=12:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --ntasks=1
#SBATCH --mem=10G
#SBATCH --job-name=medium_TO
#SBATCH --output=medium_TO-%j.log
module load Qt
module load GCC/5.1.0
./elly_peregrine parameters_medium_TO.txt
