#!/bin/bash
#SBATCH --time=12:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --ntasks=1
#SBATCH --mem=10G
#SBATCH --job-name=1000clades
#SBATCH --output=1000clades-%j.log
module load Qt
module load GCC/5.1.0
module load R/3.3.1-foss-2016a
./elly_peregrine parameters_1000clades.txt
